package com.liufuhao.crowd.exception;

/**
 * 登录失败的抛出的异常
 * @author Administrator
 *
 */
public class LoginAcctAlreadyInUseforUpdateException extends RuntimeException{

	private static final long serialVersionUID = 1L;

	public LoginAcctAlreadyInUseforUpdateException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public LoginAcctAlreadyInUseforUpdateException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

	public LoginAcctAlreadyInUseforUpdateException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public LoginAcctAlreadyInUseforUpdateException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public LoginAcctAlreadyInUseforUpdateException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}

	
}
